server:
 port: 9004
 
 
 
spring:
 datasource:
  url: "jdbc:mysql://localhost:3307/bd_restaurante_5to_ciclo?useSSL=false&serverTimeZone=UTC"
  username: "root1"
  password: "123456"
 jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate: "org.hibernate.dialect.MySqlDialect"

loggin:
 level:
  org:
   hibernate:
    SQL: DEBUG
    type: TRACE
    
    
